name: Render a CV
on:
  push:
    branches:
      - main
      - master
    paths:
      - "_data/cv.yml"
      - "assets/rendercv/resume.tex"
      - "assets/rendercv/design.yaml"
      - "assets/rendercv/locale.yaml"
      - "assets/rendercv/settings.yaml"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  rendercv:
    name: Render CV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends texlive-latex-base texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra
      - name: Compile resume.tex
        run: bash bin/compile-resume.sh
      - name: Upload rendercv_output as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: RenderCV Output
          path: assets/rendercv/rendercv_output/Karthikheyaa_Kurra_CV.pdf
      - name: Push the changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add assets/rendercv/rendercv_output/Karthikheyaa_Kurra_CV.pdf
          git diff --staged --quiet || git commit -m "chore: render the latest CV"
          git push
